sudo: false
language: node_js
node_js:
  - '12'

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint
  - yarn test:ci

after_success:
  - npx codecov
