import { subsetSum } from './subset-sum'

describe('subsetSum', () => {
  test('should determine if there is a subset sum', () => {
    let list = [3, 34, 4, 12, 5, 2]

    expect(subsetSum(list, 1)).toBe(false)
    expect(subsetSum(list, 2)).toBe(true)
    expect(subsetSum(list, 3)).toBe(true)
    expect(subsetSum(list, 4)).toBe(true)
    expect(subsetSum(list, 5)).toBe(true)
    expect(subsetSum(list, 6)).toBe(true)
    expect(subsetSum(list, 7)).toBe(true)
    expect(subsetSum(list, 8)).toBe(true)
    expect(subsetSum(list, 9)).toBe(true)
    expect(subsetSum(list, 10)).toBe(true)
    expect(subsetSum(list, 11)).toBe(true)
    expect(subsetSum(list, 12)).toBe(true)
    expect(subsetSum(list, 13)).toBe(false)
    expect(subsetSum(list, 14)).toBe(true)
    expect(subsetSum(list, 15)).toBe(true)
    expect(subsetSum(list, 16)).toBe(true)
    expect(subsetSum(list, 17)).toBe(true)
    expect(subsetSum(list, 18)).toBe(true)
    expect(subsetSum(list, 19)).toBe(true)
    expect(subsetSum(list, 20)).toBe(true)
    expect(subsetSum(list, 21)).toBe(true)
    expect(subsetSum(list, 22)).toBe(true)
    expect(subsetSum(list, 23)).toBe(true)
    expect(subsetSum(list, 24)).toBe(true)
    expect(subsetSum(list, 25)).toBe(false)
    expect(subsetSum(list, 26)).toBe(true)
    expect(subsetSum(list, 27)).toBe(false)
    expect(subsetSum(list, 28)).toBe(false)
    expect(subsetSum(list, 29)).toBe(false)
    expect(subsetSum(list, 30)).toBe(false)
    expect(subsetSum(list, 31)).toBe(false)
    expect(subsetSum(list, 32)).toBe(false)
    expect(subsetSum(list, 33)).toBe(false)
    expect(subsetSum(list, 34)).toBe(true)
    expect(subsetSum(list, 35)).toBe(false)
    expect(subsetSum(list, 36)).toBe(true)
  })
})
